# Generated by Gemma 2B via Ollama

class Solution:
    def mctFromLeafValues(self, arr: List[int]) -> int:
        n = len(arr)
        left_max = arr[0]
        right_max = arr[n - 1]

        def dfs(start, parent, left, right):
            if left == right:
                return 0

            left_max = max(left_max, arr[left])
            right_max = max(right_max, arr[right])

            if parent:
                left_max = max(left_max, left_max * right_max)
            return left_max + right_max

        return dfs(0, None, left_max, right_max)

