# Generated by Gemma 2B via Ollama

class Solution:
    def divisorGame(self, n):
        # Create a queue to store the numbers from 1 to n.
        queue = range(1, n + 1)

        # Mark the initial number as visited.
        visited = {n}

        # Initialize the first player to choose from.
        player = 1

        # Keep track of the moves made by each player.
        moves = 0

        # Iterate through the numbers in the queue.
        while queue:
            # If the current number is visited, it's not available.
            if n in visited:
                return False

            # If the current number is chosen by the player, mark it as visited.
            if player == 1:
                visited[n] = True
                moves += 1
            # If the current number is chosen by the opponent, remove it from the queue.
            else:
                queue.remove(n)

            # Switch to the other player's turn.
            player = 2 if player == 1 else 1

        # Return True if Alice wins, False otherwise.
        return True

