# Generated by Gemma 2B via Ollama

class Solution:
    def maxAlternatingSum(self, nums: List[int]) -> int:
        left, right = 0, len(nums) - 1
        max_sum = float('-inf')
        result = 0
        
        while left < right:
            sum = nums[left] - nums[right]
            result = max(result, sum)
            if left < right:
                left += 1
            if right > left:
                right -= 1
        return result

