# Generated by Gemma 2B via Ollama

class Solution:
    def maxResult(self, nums: List[int], k: int) -> int:
        n = len(nums)
        max_score = 0

        # Set up a table to store the maximum score for each index
        dp = [0] * (n + 1)

        # Initialize the first row of the table
        dp[0] = nums[0]

        # Iterate over the array
        for i in range(1, n + 1):
            # Update the maximum score for each index
            dp[i] = max(dp[i - 1], dp[i - k] + nums[i])

        # Return the maximum score
        return max_score

