# Generated by Phi-2 via Ollama

class Solution:
    def maxScore(self, nums: List[int], k: int) -> int:
        scores = [0 for i in range(len(nums))]

        for step in range(k): # Jumping with a fixed range of `k` steps
            scores[step] += nums[0] # First jump has the score equal to the first element of the list

        for i in range(1, len(nums)): # For each index after the first one
            scores[i] = max(scores[max(0, i-k):min(i+1, len(nums))]) + nums[i]

        return max(scores) # Return the maximum score
