# Generated by Gemma 2B via Ollama

class Solution:
    def squareFreeSubsets(self, nums: List[int]) -> int:
        result = 0
        for start in range(len(nums)):
            for end in range(start + 1, len(nums) + 1):
                product = nums[start:end]
                if product % 2 == 0 and product != 1:
                    result += 1
                    break
        return result % 109 + 7

