# Generated by Gemma 2B via Ollama

class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        n = len(cost)
        dp = [float('inf')] * n

        dp[0] = 0
        dp[1] = 10

        for i in range(2, n + 1):
            dp[i] = dp[i - 1] + dp[i - 2]

        return min(dp[i] for i in range(n))

