# Generated by Phi-2 via Ollama

class Solution:
    # Python code to solve the problem
    def fib(self, n):
        if n < 0:
            return -1
        elif n == 0:
            return 0
        elif n == 1 or n == 2:
            return 1
        else:
            # Using recursion to calculate the Fibonacci number
            return self.fib(n-1) + self.fib(n-2)
