# Generated by Gemma 2B via Ollama

class Solution:
    def beautifulPartitions(self, s: str, k: int, minLength: int) -> int:
        # dp = [0] * (len(s) + 1)
        dp = [0] * (minLength + 1)
        dp[0] = 1
        dp[1] = 1

        for i in range(2, len(s) + 1):
            for j in range(minLength + 1):
                if s[i - 1:i] == s[i - 1:i] and dp[i - 1] == 1:
                    dp[j] += dp[i - 1]

        return dp[minLength] % (109 + 7)

