# Generated by Gemma 2B via Ollama

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        # Create a list of lists to store the triangle
        triangle = [[1]]

        # Iterate over the rows of the triangle
        for i in range(1, numRows + 1):
            # Add the previous two rows to the current row
            row = [triangle[i - 1] + triangle[i - 2] for i in range(1, i + 1)]
            # Add the row to the triangle
            triangle.append(row)

        # Return the triangle
        return triangle

