# Generated by Gemma 2B via Ollama

class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        # dp = [float('inf')] * (amount + 1) for _ in range(len(coins) + 1)]
        dp = [float('inf')] * (amount + 1)
        dp[0] = 0

        for i, coin in enumerate(coins):
            for j in range(1, len(coins) + 1):
                if j - coin >= 0:
                    dp[j] = min(dp[j], dp[j - coin] + 1)

        return dp[amount] if dp[amount] != float('inf') else -1

