# Generated by Phi-2 via Ollama

class Solution:
    def coinChange(self,coins,amount):
        #base case if the amount is 0
        if amount == 0:
            return 0
        # if no more coins are available
        if amount < min(coins):
            return -1
        for i in range(len(coins)):
            res = self.coinChange(coins,amount-coins[i])
            # if solution is found return the minimum number of coins 
            if res != -1:
                return 1 + res
        return -1

