# Generated by Gemma 2B via Ollama

class Solution:
    def soupServings(self, n: int) -> float:
        # dp = [0] * (n + 1)
        dp = [0] * n

        # Base Case
        dp[0] = 0.5
        dp[1] = 0.5

        # Recursion for dp[i]
        for i in range(2, n + 1):
            dp[i] += dp[i - 1] * 0.25

        return dp[n]

