# Generated by Phi-2 via Ollama

class Solution:
    def probability_of_soup(n):
        a = 100
        b = 0

        for i in range(int(n/100 + 1)):
            a += 100 - 2 * (i*25)  # Each 100 ml of A, we lose 100 ml and get 50 ml of B.
            if a < 0: 
                return 0
        for i in range(int((n-a)/75 + 1)):
            b += 75 + 25*(i) # each 75ml of A, we add 100mls of B, i.e., (i+1)*100
            if b < 0: 
                return 0

        # The remaining quantity of A and B is n - a - b.
        a_remaining = n - a - b
        b_remaining = n - a - b

        # Probability that A becomes empty first, P(A) + 0.5*P(A+B=0).
        return 1/2 * (1 + min(a_remaining//50, b_remaining//100)/(n//100))
