# Generated by Gemma 2B via Ollama

class Solution:
    def getMaximumGenerated(self, n: int) -> int:
        max_value = 0
        for i in range(1, n + 1):
            if i % 2 == 0:
                max_value = max(max_value, nums[i])
            else:
                max_value = max(max_value, nums[i] + nums[i - 1])
        return max_value

