# Generated by Phi-2 via Ollama

class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        if not nums or len(nums) == 0 or k == 0:
            return []
        ans = [max(nums[i : i + k]) for i in range(len(nums) - k + 1)]
        return ans
