# Generated by Gemma 2B via Ollama

class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        n = len(prices)
        max_profit = 0

        # consider all possible buy and sell dates for the stock
        for i in range(1, n):
            for j in range(i + 1, n):
                profit = prices[i] - prices[j]
                if profit > max_profit:
                    max_profit = profit

        return max_profit

