# Generated by Gemma 2B via Ollama

class Solution:
    def dieSimulator(self, n: int, rollMax: List[int]) -> int:
        # Create a dictionary to store the count of each number of rolls
        count = {}
        
        # Iterate over the rollMax list
        for i, num in enumerate(rollMax):
            # If the number is already in the dictionary, increment its count
            if i in count:
                count[i] += 1
            else:
                count[i] = 1
                
        # Initialize the result to 0
        result = 0
        
        # Iterate over the dictionary and add the number of sequences for each number of rolls
        for num, count in count.items():
            result += count * (count - 1) // 2
        
        # Return the result modulo 109 + 7
        return result % (109 + 7)

