# Generated by Gemma 2B via Ollama

class Solution:
    def uniqueLetterString(self, s: str) -> int:
        """
        :type s: str
        :rtype: int
        """
        # Create a set of all the unique characters in the string.
        unique_chars = set(s)

        # Initialize the sum to 0.
        count = 0

        # Iterate over the string and count the number of occurrences of each character in the set.
        for char in s:
            if char in unique_chars:
                count += 1

        # Return the sum of the number of occurrences of each character.
        return count

