# Generated by Phi-2 via Ollama

class Solution:
    def countUniqueChars(s):
        unique = set()
        count = 0
        for i in range(len(s)):
            substring = s[i]
            for j in range(1, len(s)-i+1):
                if substring not in unique:
                    unique.add(substring)
                    count += 1
                else:
                    break
        return count
    ```
