# Generated by Gemma 2B via Ollama

class Solution:
    def getRow(self, rowIndex):
        """
        :type rowIndex: int
        :rtype: List[int]
        """
        # Initialize the output row with the current row value
        output = [rowIndex]

        # Iterate over the previous row in the triangle
        for i in range(rowIndex):
            # Add the two previous elements to get the current element
            output.append(output[i] + output[i - 1])

        # Return the output row
        return output

