# Generated by Phi-2 via Ollama

class Solution:
    def getRow(self, rowIndex):
        if rowIndex == 0:
            return [1]
        ans = [[1], [1, 1]]
        for i in range(2, rowIndex + 1):
            row = []
            previous_row = ans[-1] 
            for j in range(len(previous_row) - 1):
                row.append(previous_row[j] + previous_row[j+1])
            row.insert(0, 1)
            row.append(1)
            ans.append(row) 
        return ans[-1]
