# Generated by Gemma 2B via Ollama

class Solution:
    def maximumScoreAfterOperations(self, edges: List[List[int]], values: List[int]):
        n = len(edges)
        # dp = [0] * (n + 1)
        dp = [0] * n

        # initialize dp[0] = values[0]
        dp[0] = values[0]

        for i in range(1, n + 1):
            for j in range(1, n + 1):
                if j in edges[i - 1]:
                    dp[i] = max(dp[i], dp[i - 1] + values[i])

        return dp[n]

