# Generated by Gemma 2B via Ollama

class Solution:
    def numWays(self, steps, arrLen: int) -> int:
        # dp = [0] * (arrLen + 1)
        dp = [0] * (arrLen + 1)
        dp[0] = 1

        for i in range(1, arrLen + 1):
            for j in range(1, arrLen + 1):
                if j - i >= 1:
                    dp[j] += dp[j - i]

        return dp[0] % 109 + 7

