# Generated by Phi-2 via Ollama

class Solution:
    def totalWays(self, steps: int, arrLen: int) -> str:
        a = [0] * (arrLen + 1)
        a[1:] = [1] * arrLen
        for i in range(2, steps + 1):
            a = [(a[j - 1] + a[j] + a[-1 - j]) % (10**9 + 7) for j in range(arrLen)]
        return str(a[0])
