# Generated by Gemma 2B via Ollama

class Solution:
    def maxDotProduct(self, nums1: List[int], nums2: List[int]) -> int:
        # dp = [0] * (len(nums1) + 1)
        dp = [0] * len(nums2)

        max_dot_product = 0

        for i in range(len(nums1)):
            for j in range(len(nums2)):
                # dp[i] = max(dp[i], dp[i - nums1[i]]) + dp[j - nums2[j]]
                dp[i] = max(dp[i], dp[i - nums1[i]] + nums2[j]) if j >= nums1[i] else dp[i]

        return max_dot_product

