# Generated by Gemma 2B via Ollama

class Solution:
    def subarrayBitwiseORs(self, arr: List[int]) -> int:
        result = 0
        for i in range(len(arr)):
            for j in range(i + 1, len(arr) + 1):
                result ^= arr[i]
        return result

