# Generated by Phi-2 via Ollama

class Solution:
    def numDistinct(self, A):
        n = len(A)
        or_values = set()
        
        for i in range(2 ** n):
            subset = [A[j] for j in range(n) if (i & 2**j)] 
            if subset:
                or_values.add(sum(subset))

        return len(or_values)
