# Generated by Gemma 2B via Ollama

class Solution:
    def minFlips(self, s: str) -> int:
        left = 0
        right = len(s) - 1
        ans = 0

        while left < right:
            if s[left] == s[right]:
                left += 1
                right -= 1
            else:
                ans += 1
                left += 1

        return ans

