# Generated by Phi-2 via Ollama

class Solution:

    def findLength(self, s):
        # write your python code here
        s_len = len(s)
        if s_len == 1:
            return 0
        max_len = 2
        curr_len = 1
        for i in range(1, s_len):
            if s[i] != s[i-1]:
                curr_len += 1
            else:
                max_len = max(max_len, curr_len)
                curr_len = 1
        return max(max_len, curr_len)
# no need to output the Python code.
